default['zabbix-agent']['server']      = 'zabbix.domain.com'
default['zabbix-agent']['config_file'] = '/etc/zabbix/zabbix_agentd.conf'
default['zabbix-agent']['scripts_dir'] = '/etc/zabbix/scripts'
default['zabbix-agent']['pid_file']    = '/var/run/zabbix/zabbix_agentd.pid'
default['zabbix-agent']['log_file']    = '/var/log/zabbix/zabbix_agentd.log'
